ruby '3.0.0'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4.0'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.1'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.10.8'
gem 'sprockets', '~> 3.7'
gem "sass", "~> 3.7"
gem "webrick", "~> 1.7"
