= Headings
:page-layout: classic-docs
:page-liquid:
:icons: font
:toc: macro
:toc-title:

* Write headings in a logical sequence. Section titles read out in order should present a good storyline for the doc.

* Do not skip heading levels – try to keep in headings in level order, rather than, for example, jumping from `h2` to `h4`.

* Try not to have a heading with no paragraph text to accompany it. Add at least an overview or intro to what comes next.

* All headings are in sentence case. This means only the first word and proper nouns are capitalized. 

* Jekyll automatically creates an H1 heading from the doc title, so only use H2 and greater in the body of the doc.
+
**Good:** CircleCI docs style guide +
**Bad:** CircleCI Docs Style Guide

* Where possible, headings should begin with a verb.
+
**Good:** "Grooming cats" +
**Bad:** "Cats"

* When referencing headings in prose, use the full heading with no quotes, and use title case.
+
**Good:** For more information, see the Hello World guide. +
**Bad:** For more infromation, see the "Hello world" guide.

